"""Initial migration.

Revision ID: 28367bc63370
Revises: 
Create Date: 2023-08-10 14:54:24.698133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28367bc63370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=15), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
