"""empty message

Revision ID: 63e432a21f6e
Revises: b0f569bb7288
Create Date: 2023-09-15 16:03:43.440035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e432a21f6e'
down_revision = 'b0f569bb7288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.drop_constraint('event_id', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epoch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('epoch_id', 'epoch', ['epoch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('epoch_id')

    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
