"""empty message

Revision ID: 6fc4e3ae6a01
Revises: bedff43f6e05
Create Date: 2023-09-16 17:28:47.900110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc4e3ae6a01'
down_revision = 'bedff43f6e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_events', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.drop_column('has_events')

    # ### end Alembic commands ###
