"""empty message

Revision ID: b0f569bb7288
Revises: a107a445f46e
Create Date: 2023-09-15 14:21:49.052869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f569bb7288'
down_revision = 'a107a445f46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('event_id', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('user_campaign', schema=None) as batch_op:
        batch_op.alter_column('callsign',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_campaign', schema=None) as batch_op:
        batch_op.alter_column('callsign',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
