"""empty message

Revision ID: cd9f54db8230
Revises: 6fc4e3ae6a01
Create Date: 2023-09-22 14:05:04.747460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9f54db8230'
down_revision = '6fc4e3ae6a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.alter_column('has_events',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_time', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('hide_time')

    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.alter_column('has_events',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=sa.sql.expression.false())

    # ### end Alembic commands ###
