"""empty message

Revision ID: d08c22b5fe58
Revises: a29ebc70697f
Create Date: 2023-10-04 17:43:03.887549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08c22b5fe58'
down_revision = 'a29ebc70697f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_month', sa.Integer(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('second')
        batch_op.drop_column('minute')
        batch_op.drop_column('hour')
        batch_op.drop_column('day')
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.drop_column('end_month')
        batch_op.drop_column('end_year')
        batch_op.drop_column('start_month')
        batch_op.drop_column('start_year')

    # ### end Alembic commands ###
