"""empty message

Revision ID: da4127ee6ee4
Revises: 63e432a21f6e
Create Date: 2023-09-15 16:13:53.835544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4127ee6ee4'
down_revision = '63e432a21f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_epoch')
    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.drop_constraint('event_id', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epoch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("epoch_id", 'epoch', ['epoch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('epoch_id')

    with op.batch_alter_table('epoch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('event_id', 'event', ['event_id'], ['id'])

    op.create_table('_alembic_tmp_epoch',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=250), nullable=False),
    sa.Column('start_date', sa.VARCHAR(), nullable=False),
    sa.Column('end_date', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
