from flask import make_response, jsonify

from app import db



class Result:
    """ Result object generated by SearchEngine """

    def __init__(self):
        self.relevenance = 0
        self.object = None
        self.excerpt = ""



class SearchEngine:

    """ Search engine class for searching within a campaign from the Advanced Search page. 

            Parameters:
            --------------------------------------
                results : list
                    List of Results objects.
            --------------------------------------

            Methods:

                return_results(self):
                    Returns a list of results objects
            
                search_campaign(self, campaign(obj), query(str)):
                    Searches the database for entries that match
                    the given search query, and creates Result
                    objects for each match. Appends them to
                    self.results.    
    """

    def __init__(self):
        self.results = []

  
    def return_results(self):

        for result in self.results:
            pass


        return self.results

    

    def search_campaign(self, campaign, query):
        pass
     
